### ISSUE TITLE
Support 2.1.18

### ISSUE THREAD

**Issue by panuhorsmalahti** [kazuho/force-dedupe-git-modules#6]
There are problems with latest npm releases, namely version 2.1.18. It appears that npm has changed the format of the _from field of installed package.json files. Sometimes npm installs a package from the npm cache and adds something like "c:\temp\npm\cache" (the path is just from memory) to the _from field. In these cases the _resolved field has something like "git://foobar".

**Comment by Jin-Kim** [comment]
Hi @panuhorsmalahti. I made a pull request #5 for this a week ago.
And @kazuho, please merge this :sweat_smile:

**Comment by kazuho** [comment]
@Jin-Kim Sorry for being late; merged to master.

**Comment by Jin-Kim** [comment]
@kazuho Thank you very much!! :+1:

**Comment by Jin-Kim** [comment]
@kazuho please update on npmjs.com too. :sweat_smile:

**Comment by kazuho** [comment]
@Jin-Kim @panuhorsmalahti Would you mind if I added you two as the maintainer of the sotftware on both GitHub and npmjs.org?  I am not using node.js very much these days and it is likely that I would continue to be the bottleneck.

**Comment by Jin-Kim** [comment]
@kazuho OK. As I know, this dedupe feature will be in next major release of npm. I'll manage this until then. Thanks.

**Comment by kazuho** [comment]
@Jin-Kim added as collab of this repository.  May I ask your npmjs.org username so that I could add you as the owner?

**Comment by panuhorsmalahti** [comment]
@kazuho I can also be a maintainer.

**Comment by kazuho** [comment]
@panuhorsmalahti Thank you!  I have added you also as the maintainer of the github repo.  Please let me know your npmjs.org account.

**Comment by golbin** [comment]
@kazuho I'm sorry. I'd just changed my account name. (previously Jin-Kim) And this is my npmjs account.

**Comment by kazuho** [comment]
@golbin Thank you!  Added as owner on npmjs.org.

**Comment by golbin** [comment]
@kazuho I just published new version on npmjs. Thanks!

**Comment by panuhorsmalahti** [comment]
@kazuho my npm username is nawitus

**Comment by kazuho** [comment]
@golbin Thank you!
@panuhorsmalahti Thank you! added as owner.
